syntax = "proto3";

package echo;

service EchoService {
  //we created only 2 remote procedure calls - sayHello with argument HelloRequest that takes input name
  //and returns HelloReplay with output message. while for StreamTime it takes TimeRequest with input everySeconds
  //and returns a stream of TimeReply with output isoTime.
  rpc SayHello(HelloRequest) returns (HelloReply) {} 
  rpc StreamTime(TimeRequest) returns (stream TimeReply) {}
}

message HelloRequest {
  string name = 1; //this is what you define in json format in postman as your request body
  //string user_id = 2;
  //repeated string product_ids = 3;
  //double total_amount = 4;
  //string status = 5;
  //string created_at = 6;
}

message HelloReply {
  string message = 1; //this is what is defined in json format in postman as your response body
}

message TimeRequest {
  int32 everySeconds = 1; //this is what you define in json format in postman as your request body
}

message TimeReply {
  string isoTime = 1; //this is what is defined in json format in postman as your response body
}
